# Theoretical Question

# Practical Question

In [6]:
#Answer-1 
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, (3, 3))

# Interchange rows and columns (transpose the array)
transposed_arr = arr.T

arr, transposed_arr

(array([[ 62,  55,  98],
        [ 70,  41, 100],
        [ 80,  88,  55]]),
 array([[ 62,  70,  80],
        [ 55,  41,  88],
        [ 98, 100,  55]]))

In [3]:
#Answer-2
# Generate a 1D array with 10 elements
arr = np.arange(10)

# Reshape into a 2x5 array
arr_2x5 = arr.reshape(2, 5)

# Reshape into a 5x2 array
arr_5x2 = arr.reshape(5, 2)

arr, arr_2x5, arr_5x2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [7]:
#Answer-3
# Create a 4x4 array with random float values
arr = np.random.rand(4, 4)

# Add a border of zeros, resulting in a 6x6 array
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

arr, bordered_arr

(array([[0.63707824, 0.43722555, 0.92894691, 0.00400411],
        [0.92955755, 0.0231995 , 0.11467959, 0.24099854],
        [0.01770114, 0.3669234 , 0.47846315, 0.46332923],
        [0.82424412, 0.26293874, 0.93813986, 0.77007312]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.63707824, 0.43722555, 0.92894691, 0.00400411,
         0.        ],
        [0.        , 0.92955755, 0.0231995 , 0.11467959, 0.24099854,
         0.        ],
        [0.        , 0.01770114, 0.3669234 , 0.47846315, 0.46332923,
         0.        ],
        [0.        , 0.82424412, 0.26293874, 0.93813986, 0.77007312,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

In [ ]:
QUESTION-4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
#Answer-4
arr = np.arange(10, 65, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [ ]:
QUESTION-5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

In [6]:
# #Answer-5
# Create array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply transformations
upper_case = np.char.upper(arr)
lower_case = np.char.lower(arr)
title_case = np.char.title(arr)

upper_case, lower_case, title_case

(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [7]:
#Answer-6
# Create an array of words
arr = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character
spaced_arr = np.char.join(' ', arr)

spaced_arr

array(['h e l l o', 'w o r l d', 'n u m p y'], dtype='<U9')

In [8]:
#Answer-7
# Create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

addition, subtraction, multiplication, division

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [9]:
#Answer-8
# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)

identity_matrix, diagonal_elements

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

In [ ]:
QUESTION-9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [10]:
#Answer-9
# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate a 1D array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, 100)

# Filter prime numbers
prime_numbers = arr[np.vectorize(is_prime)(arr)]

prime_numbers

array([881, 461,   2, 163, 449, 877, 317, 641, 857, 107, 593, 971, 911,
       499, 383, 601])

In [5]:
#Answer-10
import numpy as np
# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate a 1D array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, 100)

# Filter prime numbers
prime_numbers = arr[np.vectorize(is_prime)(arr)]

prime_numbers

array([569, 653, 853, 881, 431, 547, 809,  59, 151, 809, 443, 661, 223,
       151, 619])